### ISSUE TITLE
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -11)

### ISSUE THREAD

**Issue by caojiehui** [CVMI-Lab/Point-UV-Diffusion#5]
```
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -11) local_rank: 0 (pid: 2977223) of binary: /home/yingjie/miniconda3/envs/point_uv_diff/bin/python
Traceback (most recent call last):
  File "/home/yingjie/miniconda3/envs/point_uv_diff/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/yingjie/miniconda3/envs/point_uv_diff/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/yingjie/miniconda3/envs/point_uv_diff/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/yingjie/miniconda3/envs/point_uv_diff/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/yingjie/miniconda3/envs/point_uv_diff/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/yingjie/miniconda3/envs/point_uv_diff/lib/python3.8/site-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/home/yingjie/miniconda3/envs/point_uv_diff/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/yingjie/miniconda3/envs/point_uv_diff/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=========================================================
test.py FAILED
---------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
---------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-10-23_16:09:24
  host      : qwe
  rank      : 0 (local_rank: 0)
  exitcode  : -11 (pid: 2977223)
  error_file: <N/A>
  traceback : Signal 11 (SIGSEGV) received by PID 2977223
=========================================================
```

**Comment by XinYu-Andy** [comment]
> ```
> ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -11) local_rank: 0 (pid: 2977223) of binary: /home/yingjie/miniconda3/envs/point_uv_diff/bin/python
> Traceback (most recent call last):
>   File "/home/yingjie/miniconda3/envs/point_uv_diff/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/home/yingjie/miniconda3/envs/point_uv_diff/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/home/yingjie/miniconda3/envs/point_uv_diff/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
>     main()
>   File "/home/yingjie/miniconda3/envs/point_uv_diff/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
>     launch(args)
>   File "/home/yingjie/miniconda3/envs/point_uv_diff/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
>     run(args)
>   File "/home/yingjie/miniconda3/envs/point_uv_diff/lib/python3.8/site-packages/torch/distributed/run.py", line 715, in run
>     elastic_launch(
>   File "/home/yingjie/miniconda3/envs/point_uv_diff/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
>     return launch_agent(self._config, self._entrypoint, list(args))
>   File "/home/yingjie/miniconda3/envs/point_uv_diff/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
>     raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
> =========================================================
> test.py FAILED
> ---------------------------------------------------------
> Failures:
>   <NO_OTHER_FAILURES>
> ---------------------------------------------------------
> Root Cause (first observed failure):
> [0]:
>   time      : 2023-10-23_16:09:24
>   host      : qwe
>   rank      : 0 (local_rank: 0)
>   exitcode  : -11 (pid: 2977223)
>   error_file: <N/A>
>   traceback : Signal 11 (SIGSEGV) received by PID 2977223
> =========================================================
> ```

Can you provide the full stack trace?

**Comment by caojiehui** [comment]
> > ```
> > ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -11) local_rank: 0 (pid: 2977223) of binary: /home/yingjie/miniconda3/envs/point_uv_diff/bin/python
> > Traceback (most recent call last):
> >   File "/home/yingjie/miniconda3/envs/point_uv_diff/lib/python3.8/runpy.py", line 194, in _run_module_as_main
> >     return _run_code(code, main_globals, None,
> >   File "/home/yingjie/miniconda3/envs/point_uv_diff/lib/python3.8/runpy.py", line 87, in _run_code
> >     exec(code, run_globals)
> >   File "/home/yingjie/miniconda3/envs/point_uv_diff/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
> >     main()
> >   File "/home/yingjie/miniconda3/envs/point_uv_diff/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
> >     launch(args)
> >   File "/home/yingjie/miniconda3/envs/point_uv_diff/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
> >     run(args)
> >   File "/home/yingjie/miniconda3/envs/point_uv_diff/lib/python3.8/site-packages/torch/distributed/run.py", line 715, in run
> >     elastic_launch(
> >   File "/home/yingjie/miniconda3/envs/point_uv_diff/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
> >     return launch_agent(self._config, self._entrypoint, list(args))
> >   File "/home/yingjie/miniconda3/envs/point_uv_diff/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
> >     raise ChildFailedError(
> > torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
> > =========================================================
> > test.py FAILED
> > ---------------------------------------------------------
> > Failures:
> >   <NO_OTHER_FAILURES>
> > ---------------------------------------------------------
> > Root Cause (first observed failure):
> > [0]:
> >   time      : 2023-10-23_16:09:24
> >   host      : qwe
> >   rank      : 0 (local_rank: 0)
> >   exitcode  : -11 (pid: 2977223)
> >   error_file: <N/A>
> >   traceback : Signal 11 (SIGSEGV) received by PID 2977223
> > =========================================================
> > ```
> 
> Can you provide the full stack trace?

```
(point_uv_diff) yingjie@qwe:~/Point-UV-Diffusion/src$ bash test.sh
/home/yingjie/miniconda3/envs/point_uv_diff/lib/python3.8/site-packages/torch/distributed/launch.py:178: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use_env is set by default in torchrun.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
| distributed init (rank 0): env://, gpu 0
[rank: 0] Global seed set to 12345
------split_files = /data1/chc/dataset_3d/point_uv_diffusion/final_split_files 04379243 train_text
------split_files = /data1/chc/dataset_3d/point_uv_diffusion/final_split_files 04379243 test_text
------split_files = /data1/chc/dataset_3d/point_uv_diffusion/final_split_files 04379243 test_text
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -11) local_rank: 0 (pid: 3322323) of binary: /home/yingjie/miniconda3/envs/point_uv_diff/bin/python
Traceback (most recent call last):
  File "/home/yingjie/miniconda3/envs/point_uv_diff/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/yingjie/miniconda3/envs/point_uv_diff/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/yingjie/miniconda3/envs/point_uv_diff/lib/python3.8/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/yingjie/miniconda3/envs/point_uv_diff/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/yingjie/miniconda3/envs/point_uv_diff/lib/python3.8/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/yingjie/miniconda3/envs/point_uv_diff/lib/python3.8/site-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/home/yingjie/miniconda3/envs/point_uv_diff/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/yingjie/miniconda3/envs/point_uv_diff/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=========================================================
test.py FAILED
---------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
---------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-01_11:42:43
  host      : qwe
  rank      : 0 (local_rank: 0)
  exitcode  : -11 (pid: 3322323)
  error_file: <N/A>
  traceback : Signal 11 (SIGSEGV) received by PID 3322323
=========================================================
```

The contents of test.sh are as follows:
# # test the coarse stage of image-condition model on the table dataset
CUDA_VISIBLE_DEVICES=1 python -m torch.distributed.launch --master_port 12346 --nproc_per_node 1 test.py \
experiment=table_image_coarse \
ckpt_name=../pretrain/image_condition/table_image_coarse/ckpt/ckpt.pth
